# Generated by Django 2.2.4 on 2019-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='activate',
            new_name='active',
        ),
    ]
