# Generated by Django 2.2.4 on 2019-08-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190830_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttour',
            name='adult_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clienttour',
            name='child_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clienttour',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='news.Client'),
        ),
        migrations.AddField(
            model_name='clienttour',
            name='tourpack_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourpack_id', to='news.TourPack'),
        ),
    ]
