# Generated by Django 2.2.4 on 2019-08-30 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190830_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
