# Generated by Django 2.2.4 on 2019-08-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_clienttour_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpack',
            name='tour_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
